spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/bharatconnect
    username: bharatconnect
    password: bharatconnect
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect