package com.project.BharatConnect.gamification.entity;

public enum PointAction {
    // Content Creation
    POST_TEXT,
    POST_CREATED_TEXT,
    POST_IMAGE,
    POST_CREATED_IMAGE,
    POST_VIDEO,
    POST_CREATED_VIDEO,
    POST_POLL,
    POST_CREATED_POLL,
    POST_QUIZ,
    POST_CREATED_QUIZ,
    POST_REPOST,
    POST_CREATED_REPOST,

    // Comments
    COMMENT_CREATE,
    COMMENT_CREATED,
    REPLY_CREATE,
    REPLY_CREATED,

    // Social Received
    LIKE_RECEIVED_CONTENT,
    LIKE_RECEIVED_COMMENT,
    COMMENT_RECEIVED_CONTENT,
    REPOST_RECEIVED_CONTENT,

    // Interactive
    POLL_VOTE,
    POLL_VOTED,
    QUIZ_ANSWER,
    QUIZ_ANSWERED,
    QUIZ_CORRECT_BONUS,

    // Streaks
    STREAK_DAILY,
    STREAK_MILESTONE,
    STREAK_MILESTONE_BONUS,

    // First time bonuses
    FIRST_POST_BONUS,
    FIRST_COMMENT_BONUS,
    FIRST_LIKE_GIVEN_BONUS,

    // Quests & Achievements
    QUEST_COMPLETED,
    DAILY_QUEST_COMPLETED,
    ACHIEVEMENT_UNLOCKED,

    // Reversals
    REVERSAL_CONTENT_DELETED,
    POST_DELETED_REVERSAL,
    REVERSAL_COMMENT_DELETED,
    COMMENT_DELETED_REVERSAL,
    REVERSAL_CONTENT_UNLIKED,
    REVERSAL_COMMENT_UNLIKED,
    LIKE_REMOVED,

    // Admin
    ADMIN_ADJUST,
    ADMIN_PENALTY
}
